[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "crypto-alpha-lab"
version = "0.1.0"
description = "Quantitative cryptocurrency alpha research library."
authors = [
    { name = "Emem Ayara" }
]
requires-python = ">=3.12"

dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "matplotlib",
    "plotly",
    "scikit-learn",
    "statsmodels",
    "yfinance",
    "pyarrow",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88